# .github/workflows/pages.yml
name: Build & Deploy Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

# 同時に複数デプロイが走らないように
concurrency:
  group: "pages"
  cancel-in-progress: false

permissions:
  contents: read       # checkout 用
  pages: write         # デプロイ用
  id-token: write      # OIDC 用

jobs:
  # ---------- 1) Build job ----------
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Poetry & dependencies
        run: |
          pip install poetry
          poetry install --no-root --no-interaction

      - name: Generate static site
        run: poetry run python gen_site.py

      # v3 に更新！
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs     # ← 静的サイトを置いたフォルダ

  # ---------- 2) Deploy job ----------
  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
