# .github/workflows/pages.yml
name: Deploy Pages

on:
  push:
    branches: [main]        # ← デプロイしたいブランチ
  workflow_dispatch:

permissions:
  contents: read            # checkout
  pages: write              # デプロイ
  id-token: write           # OIDC

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # ① リポジトリ取得
      - uses: actions/checkout@v4

      # ② Pages 用パラメータを設定（必須！）
      - uses: actions/configure-pages@v3

      # ③ docs/ をアーティファクト化（自動で github-pages 名になる）
      - uses: actions/upload-pages-artifact@v3
        with:
          path: docs

      # ④ デプロイ
      - uses: actions/deploy-pages@v2
