name: Deploy Pages
on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false   # 同一ブランチの同時デプロイ衝突を防止

jobs:
  deploy:
    runs-on: ubuntu-latest

    # ───────────────────────────────
    # environment をここで宣言
    # 「github-pages」という名前は固定
    # URL には deploy ステップの outputs.page_url を反映
    # ───────────────────────────────
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}

    steps:
      # 1. リポジトリ取得
      - uses: actions/checkout@v4

      # 2. Pages 用設定 (必須)
      - uses: actions/configure-pages@v3

      # 3. docs/ → artifact: github-pages
      - uses: actions/upload-pages-artifact@v3
        with:
          path: docs

      # 4. デプロイ
      - id: deploy
        uses: actions/deploy-pages@v4
