# .github/workflows/pages.yml
name: Deploy Pages

on:
  push:
    branches: [main]          # 公開したいブランチ
  workflow_dispatch:

permissions:
  contents: read              # checkout
  pages: write                # デプロイ
  id-token: write             # OIDC

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. リポジトリ取得
      - uses: actions/checkout@v4

      # 2. Pages 用の環境・Build ID を設定（必須）
      - uses: actions/configure-pages@v3

      # 3. docs/ をアーティファクト化（自動で名前 github-pages）
      - uses: actions/upload-pages-artifact@v3
        with:
          path: docs           # <-- ここはあなたの静的サイトフォルダ

      # 4. デプロイ
      - uses: actions/deploy-pages@v4
